# Generated by setup.py — re-run setup.py to update holdings from a new screenshot.
# Edit manually if you need fine-grained control.

HOLDINGS = [
    # {"ticker": "RKLB", "shares": 50, "avg_price": 28.50, "notes": ""},
]

WATCHLIST = []  # Tickers to watch but not currently held

REPORT_SAVE_PATH = "~/Desktop/reports/"
