"""
ReportLab PDF generator for Accountant daily brief.
Uses canvas directly for pixel-precise control.
All coordinates in points (72 pt = 1 inch). Origin is bottom-left.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas

# ── Page geometry ─────────────────────────────────────────────────────────────
PAGE_W, PAGE_H = letter   # 612 × 792 pt
MARGIN = 54               # 0.75 in
CONTENT_W = PAGE_W - 2 * MARGIN

# ── Colour palette ────────────────────────────────────────────────────────────
NAVY      = colors.HexColor("#1B2A4A")
DARK      = colors.HexColor("#1A1A1A")
BODY      = colors.HexColor("#444444")
MID_GRAY  = colors.HexColor("#888888")
FOOT_GRAY = colors.HexColor("#AAAAAA")
RULE      = colors.HexColor("#E0E0E0")
GREEN     = colors.HexColor("#27AE60")
AMBER     = colors.HexColor("#E67E22")
RED       = colors.HexColor("#C0392B")
BAR_BG    = colors.HexColor("#E8E8E8")
CARD_BG   = colors.HexColor("#F7F9FC")
CARD_BR   = colors.HexColor("#DDE3EC")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _verdict_color(verdict: str) -> Any:
    v = verdict.lower()
    if any(k in v for k in ("strong buy", "accumulate", "buy")):
        return GREEN
    if any(k in v for k in ("sell", "trim")):
        return RED
    return AMBER


def _draw_footer(c: canvas.Canvas, page_num: int, date_str: str) -> None:
    c.saveState()
    c.setFont("Helvetica", 7)
    c.setFillColor(FOOT_GRAY)
    txt = f"Generated by Accountant  ·  {date_str} 7:00am  ·  Personal use only  ·  Not financial advice"
    c.drawCentredString(PAGE_W / 2, 20, txt)
    c.drawRightString(PAGE_W - MARGIN, 20, f"{page_num}")
    c.restoreState()


def _section_header(c: canvas.Canvas, y: float, title: str) -> float:
    """Draw a navy section title + rule; return new y."""
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(NAVY)
    c.drawString(MARGIN, y, title.upper())
    y -= 5
    c.setStrokeColor(NAVY)
    c.setLineWidth(0.8)
    c.line(MARGIN, y, MARGIN + CONTENT_W, y)
    return y - 12


def _score_bar(c: canvas.Canvas, x: float, y: float, label: str, score: int | float) -> None:
    """Draw a labelled horizontal score bar at (x, y)."""
    label_w = 90
    bar_w   = 130
    bar_h   = 9
    bx      = x + label_w

    c.setFont("Helvetica", 7.5)
    c.setFillColor(BODY)
    c.drawString(x, y + 1, label)

    c.setFillColor(BAR_BG)
    c.rect(bx, y, bar_w, bar_h, fill=1, stroke=0)

    fill = max((score / 10) * bar_w, 1)
    c.setFillColor(GREEN if score >= 7 else AMBER if score >= 4 else RED)
    c.rect(bx, y, fill, bar_h, fill=1, stroke=0)

    c.setFont("Helvetica-Bold", 7.5)
    c.setFillColor(DARK)
    c.drawString(bx + bar_w + 6, y + 1, f"{score}/10")


def _wrapped_lines(text: str, font: str, size: float, max_w: float) -> list[str]:
    return simpleSplit(str(text), font, size, max_w)


def _draw_text_block(
    c: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    max_w: float,
    font: str = "Helvetica",
    size: float = 9,
    line_h: float = 13,
    color=None,
) -> float:
    if color:
        c.setFillColor(color)
    c.setFont(font, size)
    for line in _wrapped_lines(text, font, size, max_w):
        c.drawString(x, y, line)
        y -= line_h
    return y


# ── Cover page ────────────────────────────────────────────────────────────────

def _cover_page(
    c: canvas.Canvas,
    page: list,
    date_str: str,
    mood: str,
    is_market_closed: bool,
) -> None:
    if page[0] > 0:
        c.showPage()
    page[0] += 1

    cx = PAGE_W / 2

    # Accent left stripe
    c.setFillColor(NAVY)
    c.rect(0, 0, 8, PAGE_H, fill=1, stroke=0)

    # Title
    c.setFont("Helvetica-Bold", 52)
    c.setFillColor(NAVY)
    c.drawCentredString(cx, PAGE_H - 155, "ACCOUNTANT")

    # Rule
    c.setStrokeColor(NAVY)
    c.setLineWidth(2)
    c.line(MARGIN, PAGE_H - 174, PAGE_W - MARGIN, PAGE_H - 174)

    # Date
    c.setFont("Helvetica", 13)
    c.setFillColor(MID_GRAY)
    c.drawCentredString(cx, PAGE_H - 200, date_str)

    # Subtitle
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(DARK)
    c.drawCentredString(cx, PAGE_H - 252, "Daily Portfolio Intelligence Brief")

    # Mood
    c.setFont("Helvetica-Oblique", 12)
    c.setFillColor(BODY)
    c.drawCentredString(cx, PAGE_H - 296, mood)

    # Market-closed banner
    if is_market_closed:
        by = PAGE_H - 390
        c.setFillColor(colors.HexColor("#FFF8DC"))
        c.setStrokeColor(colors.HexColor("#C8A000"))
        c.setLineWidth(1.5)
        c.roundRect(MARGIN, by, CONTENT_W, 44, 6, fill=1, stroke=1)
        c.setFont("Helvetica-Bold", 10.5)
        c.setFillColor(colors.HexColor("#6B5000"))
        c.drawCentredString(cx, by + 16, "Markets closed — analysis based on last session")

    _draw_footer(c, page[0], date_str)


# ── Portfolio snapshot ────────────────────────────────────────────────────────

def _snapshot_page(
    c: canvas.Canvas,
    page: list,
    date_str: str,
    holdings: list,
    analyses: dict,
    finnhub_prices: dict,
) -> None:
    c.showPage()
    page[0] += 1
    y = PAGE_H - MARGIN

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(NAVY)
    c.drawString(MARGIN, y, "PORTFOLIO SNAPSHOT")
    y -= 10
    c.setStrokeColor(NAVY)
    c.setLineWidth(2)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 26

    # Column specs: (label, width, right-aligned?)
    cols = [
        ("TICKER",    56, False),
        ("SHARES",    46, True),
        ("AVG COST",  62, True),
        ("CURRENT",   62, True),
        ("TOTAL P&L", 70, True),
        ("VERDICT",   0,  False),  # fills remainder
    ]
    cols[-1] = ("VERDICT", CONTENT_W - sum(w for _, w, _ in cols[:-1]), False)

    # Header row
    c.setFont("Helvetica-Bold", 7.5)
    c.setFillColor(MID_GRAY)
    x = MARGIN
    for label, w, right in cols:
        c.drawRightString(x + w, y, label) if right else c.drawString(x, y, label)
        x += w
    y -= 6
    c.setStrokeColor(RULE)
    c.setLineWidth(0.5)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 18

    for holding in holdings:
        ticker    = holding["ticker"]
        shares    = holding["shares"]
        avg_price = holding["avg_price"]
        analysis  = analyses.get(ticker) or {}

        current = analysis.get("current_price") or finnhub_prices.get(ticker) or avg_price
        pnl_pct = (current - avg_price) / avg_price * 100 if avg_price else 0
        verdict = analysis.get("verdict", "Data unavailable") if analysis else "Data unavailable"

        x = MARGIN

        # Ticker
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(DARK)
        c.drawString(x, y, ticker)
        x += 56

        c.setFont("Helvetica", 9)
        c.setFillColor(BODY)

        # Shares
        c.drawRightString(x + 46, y, f"{shares:,.2f}")
        x += 46
        # Avg cost
        c.drawRightString(x + 62, y, f"${avg_price:,.2f}")
        x += 62
        # Current
        c.drawRightString(x + 62, y, f"${current:,.2f}")
        x += 62
        # P&L
        c.setFillColor(GREEN if pnl_pct >= 0 else RED)
        c.setFont("Helvetica-Bold", 9)
        c.drawRightString(x + 70, y, f"{pnl_pct:+.1f}%")
        x += 70

        # Verdict badge
        vc = _verdict_color(verdict)
        badge_text = verdict[:24]
        badge_w    = min(len(badge_text) * 6.2 + 14, 180)
        c.setFillColor(vc)
        c.roundRect(x, y - 2, badge_w, 14, 2, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 7)
        c.drawString(x + 5, y + 2, badge_text)

        y -= 24
        c.setStrokeColor(colors.HexColor("#F2F2F2"))
        c.setLineWidth(0.3)
        c.line(MARGIN, y + 10, PAGE_W - MARGIN, y + 10)

        if y < 80:
            _draw_footer(c, page[0], date_str)
            c.showPage()
            page[0] += 1
            y = PAGE_H - MARGIN

    _draw_footer(c, page[0], date_str)


# ── Individual holding page ───────────────────────────────────────────────────

def _holding_page(
    c: canvas.Canvas,
    page: list,
    date_str: str,
    holding: dict,
    analysis: dict | None,
    finnhub_price: float,
) -> None:
    c.showPage()
    page[0] += 1

    ticker    = holding["ticker"]
    avg_price = holding["avg_price"]
    shares    = holding["shares"]

    # ── Navy header strip ─────────────────────────────────────────────────
    c.setFillColor(NAVY)
    c.rect(0, PAGE_H - 68, PAGE_W, 68, fill=1, stroke=0)

    c.setFont("Helvetica-Bold", 28)
    c.setFillColor(colors.white)
    c.drawString(MARGIN, PAGE_H - 46, ticker)

    if analysis:
        verdict = analysis.get("verdict", "")
        conf    = analysis.get("confidence", "")
        vc      = _verdict_color(verdict)
        bw      = min(len(verdict) * 7.2 + 18, 190)
        bx      = PAGE_W - MARGIN - bw
        c.setFillColor(vc)
        c.roundRect(bx, PAGE_H - 56, bw, 22, 4, fill=1, stroke=0)
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(bx + 8, PAGE_H - 44, verdict[:26])
        if conf:
            c.setFont("Helvetica", 7.5)
            c.setFillColor(colors.HexColor("#B0C4DE"))
            c.drawRightString(bx - 10, PAGE_H - 44, f"Confidence: {conf}")

    y = PAGE_H - 82

    # ── Fallback card if analysis failed ─────────────────────────────────
    if not analysis:
        c.setFont("Helvetica-Bold", 13)
        c.setFillColor(RED)
        c.drawString(MARGIN, y, "Data unavailable — check manually")
        c.setFont("Helvetica", 10)
        c.setFillColor(BODY)
        c.drawString(MARGIN, y - 20, "Analysis could not be completed after 3 attempts. Please verify this position manually.")
        _draw_footer(c, page[0], date_str)
        return

    current  = analysis.get("current_price") or finnhub_price or avg_price
    pnl_pct  = (current - avg_price) / avg_price * 100 if avg_price else 0
    pnl_abs  = (current - avg_price) * shares

    # ── Urgent flag box ───────────────────────────────────────────────────
    if analysis.get("urgent_flag"):
        box_h = 52
        c.setFillColor(colors.HexColor("#FFF5F5"))
        c.setStrokeColor(RED)
        c.setLineWidth(2)
        c.roundRect(MARGIN, y - box_h, CONTENT_W, box_h, 4, fill=1, stroke=1)
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(RED)
        c.drawString(MARGIN + 8, y - 14, "URGENT — REQUIRES ATTENTION TODAY")
        reason = analysis.get("urgent_reason") or "Significant news detected. Verify before trading."
        c.setFont("Helvetica", 8.5)
        c.setFillColor(colors.HexColor("#8B0000"))
        for line in _wrapped_lines(reason, "Helvetica", 8.5, CONTENT_W - 16)[:2]:
            c.drawString(MARGIN + 8, y - 28, line)
            break
        y -= box_h + 10

    # ── Quick stats bar ───────────────────────────────────────────────────
    stats = [
        ("CURRENT PRICE",   f"${current:,.2f}"),
        ("AVG BUY PRICE",   f"${avg_price:,.2f}"),
        ("SHARES HELD",     f"{shares:,.2f}"),
        ("TOTAL P&L",       f"{pnl_pct:+.1f}%  (${pnl_abs:+,.0f})"),
    ]
    col_w = CONTENT_W / 4
    for i, (lbl, val) in enumerate(stats):
        sx = MARGIN + i * col_w
        c.setFont("Helvetica", 7)
        c.setFillColor(MID_GRAY)
        c.drawString(sx, y, lbl)
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(GREEN if (i == 3 and pnl_pct >= 0) else RED if (i == 3) else DARK)
        c.drawString(sx, y - 14, val)
    y -= 36

    c.setStrokeColor(RULE)
    c.setLineWidth(0.5)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 14

    # ── Scores ────────────────────────────────────────────────────────────
    y = _section_header(c, y, "SCORES")
    scores = analysis.get("scores", {})
    score_items = [
        ("Fundamentals", scores.get("fundamentals", 0)),
        ("Valuation",    scores.get("valuation", 0)),
        ("Momentum",     scores.get("momentum", 0)),
        ("Macro",        scores.get("macro", 0)),
    ]
    half = CONTENT_W / 2
    for i, (lbl, sc) in enumerate(score_items):
        bx = MARGIN + (i % 2) * half
        _score_bar(c, bx, y, lbl, sc)
        if i % 2 == 1:
            y -= 20
    y -= 14

    c.setStrokeColor(RULE)
    c.setLineWidth(0.4)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 14

    # ── Thesis ────────────────────────────────────────────────────────────
    y = _section_header(c, y, "INVESTMENT THESIS")
    thesis = analysis.get("thesis", "")
    y = _draw_text_block(c, thesis, MARGIN, y, CONTENT_W, "Helvetica", 9.5, 13.5, BODY)
    y -= 10

    c.setStrokeColor(RULE)
    c.setLineWidth(0.4)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 14

    # ── Bull / Risk columns ───────────────────────────────────────────────
    col_w2  = CONTENT_W / 2 - 10
    right_x = MARGIN + col_w2 + 20

    c.setFont("Helvetica-Bold", 8.5)
    c.setFillColor(GREEN)
    c.drawString(MARGIN, y, "BULL CATALYSTS")
    c.setFillColor(RED)
    c.drawString(right_x, y, "KEY RISKS")
    y -= 14

    cy_l = y
    catalysts = analysis.get("bull_catalysts", [])
    for item in catalysts:
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.HexColor("#1A6B3A"))
        c.drawString(MARGIN, cy_l, "▲")
        cy_l = _draw_text_block(c, item, MARGIN + 11, cy_l, col_w2 - 11, "Helvetica", 8, 11, BODY) - 3

    cy_r = y
    risks = analysis.get("key_risks", [])
    for item in risks:
        c.setFont("Helvetica", 8)
        c.setFillColor(RED)
        c.drawString(right_x, cy_r, "▼")
        cy_r = _draw_text_block(c, item, right_x + 11, cy_r, col_w2 - 11, "Helvetica", 8, 11, BODY) - 3

    y = min(cy_l, cy_r) - 14

    c.setStrokeColor(RULE)
    c.setLineWidth(0.4)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 14

    # ── Price targets ─────────────────────────────────────────────────────
    y = _section_header(c, y, "PRICE TARGETS")
    targets = [
        ("12-MONTH TARGET", f"${analysis.get('price_target_12m', 0):,.2f}"),
        ("ENTRY ZONE",      str(analysis.get("entry_zone", "—"))),
        ("STOP LOSS",       f"${analysis.get('stop_loss', 0):,.2f}"),
    ]
    tw = CONTENT_W / 3
    for i, (lbl, val) in enumerate(targets):
        tx = MARGIN + i * tw
        c.setFont("Helvetica", 7)
        c.setFillColor(MID_GRAY)
        c.drawString(tx, y, lbl)
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(NAVY)
        c.drawString(tx, y - 18, val)
    y -= 40

    # Conflict note
    if analysis.get("conflict_note"):
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(AMBER)
        c.drawString(MARGIN, y, f"⚠  {analysis['conflict_note']}")

    _draw_footer(c, page[0], date_str)


# ── Opportunities page ────────────────────────────────────────────────────────

def _opportunities_page(
    c: canvas.Canvas,
    page: list,
    date_str: str,
    opportunities: list,
) -> None:
    c.showPage()
    page[0] += 1
    y = PAGE_H - MARGIN

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(NAVY)
    c.drawString(MARGIN, y, "ON THE RADAR")
    y -= 10
    c.setStrokeColor(NAVY)
    c.setLineWidth(2)
    c.line(MARGIN, y, PAGE_W - MARGIN, y)
    y -= 12
    c.setFont("Helvetica-Oblique", 8.5)
    c.setFillColor(MID_GRAY)
    c.drawString(MARGIN, y, "Stocks with similar growth profiles to your best performers — for research purposes only.")
    y -= 24

    for opp in opportunities[:3]:
        ticker   = opp.get("ticker", "?")
        name     = opp.get("company_name", "")
        price    = opp.get("current_price", 0)
        bull     = opp.get("bull_case", "")
        bear     = opp.get("bear_case", "")
        reason   = opp.get("similarity_reason", "")

        card_h = 108
        if y - card_h < 70:
            _draw_footer(c, page[0], date_str)
            c.showPage()
            page[0] += 1
            y = PAGE_H - MARGIN

        c.setFillColor(CARD_BG)
        c.setStrokeColor(CARD_BR)
        c.setLineWidth(0.5)
        c.roundRect(MARGIN, y - card_h, CONTENT_W, card_h, 6, fill=1, stroke=1)

        # Ticker + name header
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(NAVY)
        c.drawString(MARGIN + 10, y - 18, ticker)
        c.setFont("Helvetica", 10)
        c.setFillColor(BODY)
        c.drawString(MARGIN + 10 + len(ticker) * 9.5, y - 18, f"  {name}")
        if price:
            c.setFont("Helvetica-Bold", 12)
            c.setFillColor(DARK)
            c.drawRightString(PAGE_W - MARGIN - 10, y - 18, f"${price:,.2f}")

        # Similarity reason
        c.setFont("Helvetica-Oblique", 7.5)
        c.setFillColor(MID_GRAY)
        c.drawString(MARGIN + 10, y - 32, f"Why: {str(reason)[:95]}")

        # Bull
        c.setFont("Helvetica-Bold", 7.5)
        c.setFillColor(GREEN)
        c.drawString(MARGIN + 10, y - 50, "BULL:")
        c.setFont("Helvetica", 7.5)
        c.setFillColor(BODY)
        bull_lines = _wrapped_lines(str(bull), "Helvetica", 7.5, CONTENT_W - 60)
        c.drawString(MARGIN + 40, y - 50, bull_lines[0] if bull_lines else "")
        if len(bull_lines) > 1:
            c.drawString(MARGIN + 40, y - 62, bull_lines[1])

        # Bear
        bear_y = y - 76 if len(bull_lines) > 1 else y - 64
        c.setFont("Helvetica-Bold", 7.5)
        c.setFillColor(RED)
        c.drawString(MARGIN + 10, bear_y, "BEAR:")
        c.setFont("Helvetica", 7.5)
        c.setFillColor(BODY)
        bear_lines = _wrapped_lines(str(bear), "Helvetica", 7.5, CONTENT_W - 60)
        c.drawString(MARGIN + 40, bear_y, bear_lines[0] if bear_lines else "")

        y -= card_h + 18

    _draw_footer(c, page[0], date_str)


# ── Public entry point ────────────────────────────────────────────────────────

def generate_report(
    holdings: list,
    analyses: dict,
    opportunities: list,
    is_market_closed: bool,
    output_path: str,
    date_str: str,
    finnhub_prices: dict | None = None,
) -> None:
    if finnhub_prices is None:
        finnhub_prices = {}

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=letter)
    page = [0]  # mutable counter

    # Mood summary for cover
    attention = sum(
        1 for t, a in analyses.items()
        if a and (
            a.get("urgent_flag")
            or any(k in a.get("verdict", "").lower() for k in ("trim", "sell", "watch"))
        )
    )
    n = len(holdings)
    mood = (
        f"{attention} of {n} position{'s' if n != 1 else ''} warrant{'s' if n == 1 else ''} attention today"
    )

    _cover_page(c, page, date_str, mood, is_market_closed)
    _snapshot_page(c, page, date_str, holdings, analyses, finnhub_prices)

    for holding in holdings:
        ticker  = holding["ticker"]
        fp      = finnhub_prices.get(ticker, holding.get("avg_price", 0))
        _holding_page(c, page, date_str, holding, analyses.get(ticker), fp)

    if opportunities:
        _opportunities_page(c, page, date_str, opportunities)

    c.save()
