#!/usr/bin/env python3
"""
One-time setup: extracts holdings from a brokerage screenshot via Claude vision,
then writes config.py.

Usage:
    python setup.py
"""

import base64
import json
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

MODEL = "claude-opus-4-5"


def _encode_image(path: str) -> tuple[str, str]:
    """Return (base64_data, media_type) for a JPEG or PNG file."""
    suffix = Path(path).suffix.lower()
    if suffix in (".jpg", ".jpeg"):
        media_type = "image/jpeg"
    elif suffix == ".png":
        media_type = "image/png"
    else:
        raise ValueError(f"Unsupported image format: {suffix}. Use JPG or PNG.")
    with open(path, "rb") as f:
        return base64.standard_b64encode(f.read()).decode("utf-8"), media_type


def _extract_holdings(image_path: str, client) -> list[dict]:
    """Send screenshot to Claude and parse the extracted holdings."""
    img_data, media_type = _encode_image(image_path)

    prompt = """You are extracting brokerage holdings from a screenshot.

Look carefully at every position visible in the image and extract:
1. Ticker symbol (e.g. AAPL, MSFT, RKLB)
2. Number of shares (use 0 if not visible)
3. Average buy / cost-basis price per share in USD (use 0 if not visible)
4. Current market price per share in USD (use 0 if not visible)
5. Total market value of the position in USD (use 0 if not visible)

Return ONLY a JSON array — no prose, no markdown fences:
[
  {
    "ticker": "AAPL",
    "shares": 10.0,
    "avg_price": 150.25,
    "current_price": 175.00,
    "total_value": 1750.00,
    "notes": ""
  }
]

If a field is genuinely absent from the image, set it to 0."""

    response = client.messages.create(
        model=MODEL,
        max_tokens=2000,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": img_data,
                        },
                    },
                    {"type": "text", "text": prompt},
                ],
            }
        ],
    )

    raw = response.content[0].text.strip()
    # Strip markdown fences if Claude adds them
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    holdings = json.loads(raw)
    if not isinstance(holdings, list):
        raise ValueError("Expected a JSON array from Claude.")
    return holdings


def _pretty_print_holdings(holdings: list[dict]) -> None:
    print(f"\n{'TICKER':<8} {'SHARES':>10} {'AVG BUY':>10} {'CURRENT':>10} {'TOTAL VALUE':>14}")
    print("-" * 56)
    for h in holdings:
        print(
            f"{h['ticker']:<8} "
            f"{h['shares']:>10.2f} "
            f"${h['avg_price']:>9.2f} "
            f"${h['current_price']:>9.2f} "
            f"${h['total_value']:>13,.2f}"
        )
    print()


def _write_config(holdings: list[dict], watchlist: list[str]) -> None:
    lines = ["# Auto-generated by setup.py — re-run to refresh from a new screenshot.\n"]
    lines.append("HOLDINGS = [")
    for h in holdings:
        notes = h.get("notes", "").replace('"', '\\"')
        lines.append(
            f'    {{"ticker": "{h["ticker"]}", '
            f'"shares": {h["shares"]}, '
            f'"avg_price": {h["avg_price"]}, '
            f'"notes": "{notes}"}},'
        )
    lines.append("]\n")

    wl_repr = "[" + ", ".join(f'"{t}"' for t in watchlist) + "]"
    lines.append(f"WATCHLIST = {wl_repr}  # tickers to monitor but not held\n")
    lines.append('REPORT_SAVE_PATH = "~/Desktop/reports/"\n')

    config_path = Path(__file__).parent / "config.py"
    config_path.write_text("\n".join(lines))
    print(f"\nconfig.py written to {config_path}")


def main() -> None:
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set in .env")
        print("Create a .env file with:  ANTHROPIC_API_KEY=sk-ant-...")
        sys.exit(1)

    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    print("=" * 60)
    print("  Accountant — One-time Setup")
    print("=" * 60)
    print("\nStep 1 — Provide your brokerage holdings screenshot.")
    print("Drag the file into this terminal or paste the full path:")
    image_path = input("  Image path: ").strip().strip('"').strip("'")

    if not Path(image_path).exists():
        print(f"ERROR: File not found: {image_path}")
        sys.exit(1)

    print("\nSending screenshot to Claude for extraction…")
    try:
        holdings = _extract_holdings(image_path, client)
    except Exception as exc:
        print(f"ERROR during extraction: {exc}")
        sys.exit(1)

    _pretty_print_holdings(holdings)

    answer = input("Does this look correct? (yes to save / no to edit manually): ").strip().lower()
    if answer not in ("yes", "y"):
        print("\nNo problem. Edit config.py manually and add your holdings.")
        print("Format each entry as:")
        print('  {"ticker": "AAPL", "shares": 10, "avg_price": 150.00, "notes": ""}')
        # Still write a skeleton
        _write_config(holdings, [])
        sys.exit(0)

    print("\nStep 2 — Watchlist (tickers you want to track but don't hold yet).")
    wl_raw = input("  Enter comma-separated tickers, or press Enter to skip: ").strip()
    watchlist = [t.strip().upper() for t in wl_raw.split(",") if t.strip()]

    _write_config(holdings, watchlist)

    print("\n" + "=" * 60)
    print("  Setup complete! Next steps:")
    print("=" * 60)
    print("\n  1. Open .env and add your API keys:")
    print("       ANTHROPIC_API_KEY=sk-ant-...")
    print("       FINNHUB_API_KEY=<your key from finnhub.io>")
    print("\n  2. Test a dry-run:")
    print("       python accountant.py --now")
    print("\n  3. Schedule daily 7am runs:")
    print("       python scheduler.py")
    print("\n  Get your Anthropic key at: https://console.anthropic.com")
    print("  Get your Finnhub key at:   https://finnhub.io/dashboard (free tier is sufficient)")
    print()


if __name__ == "__main__":
    main()
